"""Short, slide-based lessons. Slide types: intro, concept, formula, example, tip, try."""

LESSONS: dict[str, dict] = {
    "quadratic": {
        "title": "Quadratic Equations",
        "summary": "Learn what a quadratic equation is and how to solve one by factorisation.",
        "minutes": 6,
        "slides": [
            ("intro", "What is a quadratic equation?", {"emoji": "📐", "body": "A quadratic equation is an equation where the highest power of x is 2.", "points": ["x² + 5x + 6 = 0 ✓ quadratic", "2x + 3 = 0 ✗ linear (power 1)", "x³ − 1 = 0 ✗ cubic (power 3)"]}),
            ("formula", "Standard form", {"formula": "ax² + bx + c = 0", "body": "a, b and c are constants, and a ≠ 0.", "note": "In 3x² − 5x + 2 = 0: a = 3, b = −5, c = 2"}),
            ("example", "Example", {"example": "Solve x² + 5x + 6 = 0", "steps": ["Find two numbers that multiply to 6 and add to 5 → 2 and 3", "Factorise: (x + 2)(x + 3) = 0", "Set each bracket to zero: x + 2 = 0 or x + 3 = 0"], "answer": "x = −2 or x = −3"}),
            ("concept", "Why factorisation works", {"body": "If two numbers multiply to give 0, at least one of them must be 0.", "highlight": "If A × B = 0, then A = 0 or B = 0", "points": ["Always rearrange so one side is 0 first", "Each bracket gives one root"]}),
            ("tip", "Watch the signs!", {"body": "The roots have the OPPOSITE sign of the numbers in the brackets.", "points": ["(x − 4)(x + 1) = 0 → x = 4 or x = −1", "Check: substitute your answer back into the equation"]}),
            ("try", "Try it yourself", {"question": "Solve x² − 7x + 10 = 0", "options": ["x = 2 or x = 5", "x = −2 or x = −5", "x = 1 or x = 10", "x = −1 or x = −10"], "answer": 0, "explanation": "−2 and −5 multiply to 10 and add to −7, so (x − 2)(x − 5) = 0 → x = 2 or x = 5."}),
        ],
    },
    "linear": {
        "title": "Linear Equations",
        "summary": "Solve one-variable and simultaneous linear equations.",
        "minutes": 5,
        "slides": [
            ("intro", "What is a linear equation?", {"emoji": "⚖️", "body": "A linear equation has variables with power 1. Its graph is a straight line.", "points": ["3x + 4 = 19", "y = 2x − 1"]}),
            ("concept", "Keep it balanced", {"body": "Whatever you do to one side, do to the other side.", "highlight": "Goal: get x alone on one side", "points": ["Undo + and − first", "Then undo × and ÷"]}),
            ("example", "Example", {"example": "Solve 3x + 4 = 19", "steps": ["Subtract 4 from both sides: 3x = 15", "Divide both sides by 3"], "answer": "x = 5"}),
            ("example", "Simultaneous equations", {"example": "x + y = 10 and x − y = 4", "steps": ["Add the equations: 2x = 14 → x = 7", "Substitute into x + y = 10: 7 + y = 10"], "answer": "x = 7, y = 3"}),
            ("try", "Try it yourself", {"question": "Solve 5x − 6 = 24", "options": ["x = 6", "x = 3.6", "x = 30", "x = 4"], "answer": 0, "explanation": "Add 6: 5x = 30. Divide by 5: x = 6."}),
        ],
    },
    "functions": {
        "title": "Functions",
        "summary": "Use function notation, find inverse and composite functions.",
        "minutes": 6,
        "slides": [
            ("intro", "What is a function?", {"emoji": "🔁", "body": "A function is a rule that gives exactly ONE output for each input.", "points": ["Input x → rule → output f(x)", "f(x) = 2x + 3 means 'double, then add 3'"]}),
            ("example", "Evaluating a function", {"example": "If f(x) = 2x + 3, find f(4)", "steps": ["Replace x with 4: f(4) = 2(4) + 3", "= 8 + 3"], "answer": "f(4) = 11"}),
            ("formula", "Inverse function", {"formula": "f⁻¹ undoes f", "body": "To find f⁻¹(x): let y = f(x), make x the subject, then swap.", "note": "f(x) = 2x + 3 → f⁻¹(x) = (x − 3) / 2"}),
            ("concept", "Composite functions", {"body": "fg(x) means apply g first, then f.", "highlight": "fg(x) = f(g(x))", "points": ["Work from the inside out", "fg(x) is usually NOT equal to gf(x)"]}),
            ("try", "Try it yourself", {"question": "If f(x) = 3x − 1, find f(5)", "options": ["14", "15", "16", "4"], "answer": 0, "explanation": "f(5) = 3(5) − 1 = 15 − 1 = 14."}),
        ],
    },
    "trigonometry": {
        "title": "Trigonometry",
        "summary": "Use sine, cosine and tangent in right-angled triangles.",
        "minutes": 6,
        "slides": [
            ("intro", "Right-angled triangles", {"emoji": "📏", "body": "Trigonometry links the angles and sides of right-angled triangles.", "points": ["Hypotenuse: the longest side, opposite the right angle", "Opposite: across from angle θ", "Adjacent: next to angle θ"]}),
            ("formula", "SOH CAH TOA", {"formula": "sin θ = opp/hyp   cos θ = adj/hyp   tan θ = opp/adj", "body": "Remember it as SOH-CAH-TOA.", "note": "Label the sides from the angle you are using."}),
            ("example", "Example", {"example": "A right triangle has opposite = 3, adjacent = 4, hypotenuse = 5. Find sin θ.", "steps": ["sin θ = opposite / hypotenuse", "= 3 / 5"], "answer": "sin θ = 0.6"}),
            ("tip", "Special angles", {"body": "Memorise these — they appear often in SPM.", "points": ["sin 30° = 0.5", "cos 60° = 0.5", "tan 45° = 1"]}),
            ("try", "Try it yourself", {"question": "Opposite = 5, hypotenuse = 13. What is sin θ?", "options": ["5/13", "12/13", "5/12", "13/5"], "answer": 0, "explanation": "sin θ = opposite / hypotenuse = 5/13."}),
        ],
    },
    "statistics": {
        "title": "Statistics",
        "summary": "Describe data using mean, median, mode and range.",
        "minutes": 5,
        "slides": [
            ("intro", "Making sense of data", {"emoji": "📊", "body": "Statistics help us summarise a set of numbers with one value.", "points": ["Mean = average", "Median = middle value", "Mode = most frequent", "Range = largest − smallest"]}),
            ("formula", "Mean", {"formula": "Mean = sum of data ÷ number of data", "body": "Add everything up, then divide.", "note": "2, 4, 6 → (2 + 4 + 6) ÷ 3 = 4"}),
            ("example", "Median", {"example": "Find the median of 7, 3, 9, 1, 5", "steps": ["Arrange in order: 1, 3, 5, 7, 9", "Pick the middle value"], "answer": "Median = 5"}),
            ("tip", "Even number of values?", {"body": "The median is the mean of the two middle values.", "points": ["1, 3, 5, 7 → (3 + 5) ÷ 2 = 4"]}),
            ("try", "Try it yourself", {"question": "Find the range of 4, 11, 7, 2, 9", "options": ["9", "7", "11", "6.6"], "answer": 0, "explanation": "Range = 11 − 2 = 9."}),
        ],
    },
    "indices": {
        "title": "Indices",
        "summary": "Apply the laws of indices to simplify expressions.",
        "minutes": 5,
        "slides": [
            ("intro", "What is an index?", {"emoji": "🔢", "body": "An index (power) tells you how many times to multiply a number by itself.", "points": ["2⁴ = 2 × 2 × 2 × 2 = 16", "Base = 2, index = 4"]}),
            ("formula", "Laws of indices", {"formula": "aᵐ × aⁿ = aᵐ⁺ⁿ    aᵐ ÷ aⁿ = aᵐ⁻ⁿ    (aᵐ)ⁿ = aᵐⁿ", "body": "These only work when the bases are the same.", "note": "a⁰ = 1 for any a ≠ 0"}),
            ("example", "Example", {"example": "Simplify x³ × x⁵ ÷ x²", "steps": ["Multiply: add indices → x⁸", "Divide: subtract indices → x⁸⁻²"], "answer": "x⁶"}),
            ("try", "Try it yourself", {"question": "Simplify (y²)⁴", "options": ["y⁸", "y⁶", "y¹⁶", "4y²"], "answer": 0, "explanation": "Power of a power: multiply the indices, 2 × 4 = 8."}),
        ],
    },
    "differentiation": {
        "title": "Differentiation",
        "summary": "Find gradients using the power rule.",
        "minutes": 6,
        "slides": [
            ("intro", "Rate of change", {"emoji": "📈", "body": "Differentiation finds the gradient of a curve at any point.", "points": ["dy/dx means 'the rate of change of y with respect to x'"]}),
            ("formula", "The power rule", {"formula": "d/dx (axⁿ) = anxⁿ⁻¹", "body": "Multiply by the power, then reduce the power by 1.", "note": "The derivative of a constant is 0."}),
            ("example", "Example", {"example": "Differentiate y = 4x³ + 2x", "steps": ["4x³ → 12x²", "2x → 2"], "answer": "dy/dx = 12x² + 2"}),
            ("example", "Gradient at a point", {"example": "Find the gradient of y = x² at x = 3", "steps": ["dy/dx = 2x", "Substitute x = 3: 2(3)"], "answer": "Gradient = 6"}),
            ("try", "Try it yourself", {"question": "Differentiate y = 5x²", "options": ["10x", "5x", "10x²", "2x⁵"], "answer": 0, "explanation": "5 × 2 = 10 and the power drops from 2 to 1: 10x."}),
        ],
    },
    "progressions": {
        "title": "Arithmetic Progressions",
        "summary": "Find terms and sums of arithmetic progressions.",
        "minutes": 5,
        "slides": [
            ("intro", "Patterns that add", {"emoji": "🪜", "body": "In an arithmetic progression (AP), you add the same number each time.", "points": ["3, 7, 11, 15, … (common difference d = 4)"]}),
            ("formula", "nth term", {"formula": "Tₙ = a + (n − 1)d", "body": "a is the first term, d is the common difference.", "note": "For 3, 7, 11, …: T₁₀ = 3 + 9(4) = 39"}),
            ("formula", "Sum of n terms", {"formula": "Sₙ = n/2 [2a + (n − 1)d]", "body": "Use this to add up the first n terms quickly."}),
            ("try", "Try it yourself", {"question": "Find T₅ of 2, 5, 8, …", "options": ["14", "17", "11", "15"], "answer": 0, "explanation": "a = 2, d = 3: T₅ = 2 + 4(3) = 14."}),
        ],
    },
    "electricity": {
        "title": "Electricity",
        "summary": "Understand current, voltage, resistance and electrical power.",
        "minutes": 6,
        "slides": [
            ("intro", "Electric circuits", {"emoji": "⚡", "body": "Electric current is the rate of flow of charge.", "points": ["Current I — ampere (A)", "Voltage V — volt (V)", "Resistance R — ohm (Ω)"]}),
            ("formula", "Ohm's Law", {"formula": "V = IR", "body": "Voltage equals current times resistance (at constant temperature).", "note": "Rearrange: I = V/R, R = V/I"}),
            ("concept", "Series vs parallel", {"body": "How resistors are connected changes the total resistance.", "points": ["Series: R = R₁ + R₂", "Parallel: 1/R = 1/R₁ + 1/R₂", "Two equal resistors in parallel: R = R₁ ÷ 2"]}),
            ("formula", "Electrical power", {"formula": "P = VI", "body": "Power is the rate of energy transfer, measured in watts (W).", "note": "Also: Q = It (charge = current × time)"}),
            ("try", "Try it yourself", {"question": "A 6 Ω resistor has a current of 2 A. What is the voltage?", "options": ["12 V", "3 V", "8 V", "0.33 V"], "answer": 0, "explanation": "V = IR = 2 × 6 = 12 V."}),
        ],
    },
    "forces": {
        "title": "Forces and Motion",
        "summary": "Describe motion and apply Newton's second law.",
        "minutes": 6,
        "slides": [
            ("intro", "Describing motion", {"emoji": "🚀", "body": "Velocity is speed in a given direction. Acceleration is the rate of change of velocity.", "points": ["u = initial velocity", "v = final velocity", "a = acceleration", "t = time"]}),
            ("formula", "Equation of motion", {"formula": "v = u + at", "body": "Use when acceleration is constant.", "note": "a = (v − u) / t"}),
            ("formula", "Newton's second law", {"formula": "F = ma", "body": "The net force equals mass times acceleration.", "note": "Unit of force: newton (N)"}),
            ("formula", "Momentum", {"formula": "p = mv", "body": "Momentum is mass times velocity, unit kg m s⁻¹."}),
            ("try", "Try it yourself", {"question": "A 2 kg trolley accelerates at 3 m s⁻². What is the net force?", "options": ["6 N", "1.5 N", "5 N", "0.67 N"], "answer": 0, "explanation": "F = ma = 2 × 3 = 6 N."}),
        ],
    },
    "mole": {
        "title": "The Mole Concept",
        "summary": "Convert between mass, moles and number of particles.",
        "minutes": 5,
        "slides": [
            ("intro", "Counting particles", {"emoji": "🧪", "body": "Atoms are tiny, so chemists count them in moles.", "points": ["1 mole = 6.02 × 10²³ particles (Avogadro constant)"]}),
            ("formula", "Mass and moles", {"formula": "Number of moles = mass ÷ molar mass", "body": "Molar mass is the relative formula mass in g mol⁻¹.", "note": "H₂O: 2(1) + 16 = 18 g mol⁻¹"}),
            ("example", "Example", {"example": "How many moles are in 36 g of water?", "steps": ["Molar mass of H₂O = 18 g mol⁻¹", "n = 36 ÷ 18"], "answer": "2 mol"}),
            ("try", "Try it yourself", {"question": "How many moles are in 88 g of CO₂? (C = 12, O = 16)", "options": ["2 mol", "4 mol", "0.5 mol", "1 mol"], "answer": 0, "explanation": "Molar mass of CO₂ = 12 + 2(16) = 44. n = 88 ÷ 44 = 2 mol."}),
        ],
    },
    "bonding": {
        "title": "Chemical Bonding",
        "summary": "Compare ionic and covalent bonds.",
        "minutes": 6,
        "slides": [
            ("intro", "Why atoms bond", {"emoji": "🔗", "body": "Atoms bond to achieve a stable electron arrangement (duplet or octet).", "points": ["Noble gases are already stable"]}),
            ("concept", "Ionic bonds", {"body": "Formed when electrons are TRANSFERRED from a metal to a non-metal.", "highlight": "Metal loses e⁻ → positive ion; non-metal gains e⁻ → negative ion", "points": ["Example: NaCl", "High melting points, conduct electricity when molten or in water"]}),
            ("concept", "Covalent bonds", {"body": "Formed when non-metal atoms SHARE electrons.", "highlight": "Single bond = 1 shared pair", "points": ["Example: H₂O, CO₂, CH₄", "Usually low melting points, do not conduct electricity"]}),
            ("try", "Try it yourself", {"question": "Which compound has ionic bonds?", "options": ["MgO", "CO₂", "CH₄", "H₂O"], "answer": 0, "explanation": "Magnesium (metal) transfers electrons to oxygen (non-metal), forming ions."}),
        ],
    },
    "cell": {
        "title": "Cell Biology",
        "summary": "Identify organelles and their functions.",
        "minutes": 5,
        "slides": [
            ("intro", "The basic unit of life", {"emoji": "🔬", "body": "All living things are made of cells.", "points": ["Animal cells and plant cells share many organelles", "Plant cells also have a cell wall, chloroplasts and a large vacuole"]}),
            ("concept", "Key organelles", {"body": "Each organelle has a job.", "points": ["Nucleus — controls cell activities, contains DNA", "Mitochondrion — site of cellular respiration (energy)", "Ribosome — protein synthesis", "Chloroplast — photosynthesis"]}),
            ("tip", "Memory trick", {"body": "Mitochondria are the 'power stations' of the cell.", "points": ["Active cells (like muscle cells) have many mitochondria"]}),
            ("try", "Try it yourself", {"question": "Which structure is found in plant cells but NOT animal cells?", "options": ["Cell wall", "Nucleus", "Cell membrane", "Mitochondrion"], "answer": 0, "explanation": "Only plant cells have a cellulose cell wall."}),
        ],
    },
    "independence": {
        "title": "Road to Independence",
        "summary": "Key events from the Malayan Union to the formation of Malaysia.",
        "minutes": 6,
        "slides": [
            ("intro", "Towards Merdeka", {"emoji": "🇲🇾", "body": "After World War II, the people of Malaya worked together to gain independence from Britain.", "points": ["1946 Malayan Union", "1948 Federation of Malaya", "1957 Independence"]}),
            ("concept", "Opposing the Malayan Union", {"body": "The Malayan Union (1946) reduced the power of the Malay Rulers and was strongly opposed.", "points": ["UMNO was formed in 1946, led by Dato' Onn Jaafar", "It was replaced by the Federation of Malaya in 1948"]}),
            ("concept", "Unity and negotiation", {"body": "The Alliance (Perikatan) of UMNO, MCA and MIC showed that different communities could cooperate.", "points": ["Tunku Abdul Rahman led the delegation to London in 1956", "The Reid Commission drafted the constitution"]}),
            ("concept", "Merdeka and Malaysia", {"body": "Tunku Abdul Rahman proclaimed independence at Stadium Merdeka.", "highlight": "31 August 1957 — Independence of the Federation of Malaya", "points": ["16 September 1963 — Malaysia formed with Sabah, Sarawak and Singapore", "9 August 1965 — Singapore separated"]}),
            ("try", "Try it yourself", {"question": "Who was the first Prime Minister of Malaya?", "options": ["Tunku Abdul Rahman", "Tun Abdul Razak", "Dato' Onn Jaafar", "Tun Hussein Onn"], "answer": 0, "explanation": "Tunku Abdul Rahman became the first Prime Minister and is known as Bapa Kemerdekaan."}),
        ],
    },
    "tenses": {
        "title": "Grammar: Tenses",
        "summary": "Choose the correct tense for the situation.",
        "minutes": 5,
        "slides": [
            ("intro", "Time in grammar", {"emoji": "⏰", "body": "Tenses show WHEN something happens.", "points": ["Present: I play", "Past: I played", "Future: I will play"]}),
            ("concept", "Simple present", {"body": "Used for habits and facts.", "highlight": "He/She/It + verb-s", "points": ["She walks to school every day.", "Water boils at 100°C."]}),
            ("concept", "Present perfect vs simple past", {"body": "Simple past = finished time. Present perfect = connected to now.", "points": ["I visited Penang last year. (finished time)", "I have visited Penang twice. (life experience)"]}),
            ("tip", "Signal words", {"body": "Look for clues in the sentence.", "points": ["yesterday, last week, ago → past", "every day, usually → present", "since, for, already → present perfect"]}),
            ("try", "Try it yourself", {"question": "She ___ her homework yesterday.", "options": ["finished", "finishes", "has finished", "will finish"], "answer": 0, "explanation": "'Yesterday' signals a finished time in the past → simple past."}),
        ],
    },
    "imbuhan": {
        "title": "Tatabahasa: Imbuhan",
        "summary": "Kenali awalan, akhiran, apitan dan sisipan.",
        "minutes": 5,
        "slides": [
            ("intro", "Apa itu imbuhan?", {"emoji": "✍️", "body": "Imbuhan ialah unit bahasa yang ditambah pada kata dasar untuk membentuk perkataan baharu.", "points": ["Awalan: me-, di-, ber-, pe-", "Akhiran: -an, -kan, -i", "Apitan: ke-...-an, pe-...-an", "Sisipan: -el-, -em-, -er-"]}),
            ("example", "Contoh", {"example": "Kata dasar: tulis", "steps": ["me- + tulis = menulis (aktif)", "di- + tulis = ditulis (pasif)", "tulis + -an = tulisan (kata nama)"], "answer": "Satu kata dasar, banyak makna!"}),
            ("tip", "Ayat aktif dan pasif", {"body": "Gunakan me- untuk ayat aktif dan di- untuk ayat pasif.", "points": ["Ali menendang bola. (aktif)", "Bola ditendang oleh Ali. (pasif)"]}),
            ("try", "Cuba sendiri", {"question": "Surat itu ___ oleh Siti semalam.", "options": ["ditulis", "menulis", "tulisan", "bertulis"], "answer": 0, "explanation": "Ayat pasif dengan 'oleh' memerlukan awalan di-."}),
        ],
    },
    "climate": {
        "title": "Weather and Climate",
        "summary": "Understand weather elements and Malaysia's climate.",
        "minutes": 5,
        "slides": [
            ("intro", "Weather vs climate", {"emoji": "🌦️", "body": "Weather is the daily condition of the atmosphere. Climate is the average weather over about 30 years.", "points": ["Weather: today is rainy", "Climate: Malaysia is hot and wet all year"]}),
            ("concept", "Elements of weather", {"body": "Weather is measured using instruments.", "points": ["Temperature — thermometer", "Rainfall — rain gauge", "Wind speed — anemometer", "Humidity — hygrometer"]}),
            ("concept", "Malaysia's monsoons", {"body": "Malaysia has an equatorial climate influenced by monsoon winds.", "points": ["Northeast Monsoon: Nov–Mar, heavy rain on the east coast", "Southwest Monsoon: May–Sep, drier"]}),
            ("try", "Try it yourself", {"question": "Which instrument measures wind speed?", "options": ["Anemometer", "Barometer", "Rain gauge", "Hygrometer"], "answer": 0, "explanation": "An anemometer measures wind speed."}),
        ],
    },
    "values": {
        "title": "Values in Society",
        "summary": "Responsibility, respect and living in harmony.",
        "minutes": 4,
        "slides": [
            ("intro", "Why values matter", {"emoji": "🤝", "body": "Values guide how we treat ourselves, others and the environment.", "points": ["Responsibility", "Respect", "Kindness", "Justice"]}),
            ("concept", "Harmony in diversity", {"body": "Malaysia is home to many cultures. Respecting differences builds unity.", "highlight": "Rukun Negara: Kesopanan dan Kesusilaan", "points": ["Celebrate each other's festivals", "Use polite language"]}),
            ("tip", "Reflect", {"body": "Think of one way you showed responsibility this week.", "points": ["At home", "At school", "Online"]}),
        ],
    },
}
