"""baseline studyup schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 10:27:50.177450
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('badges',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schools',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('teacher_types', sa.JSON(), nullable=False),
    sa.Column('school_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_email'), ['email'], unique=True)

    op.create_table('topics',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('school_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('form', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_topic_id'), ['topic_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('space', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_space'), ['space'], unique=False)

    op.create_table('question_sets',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_sets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_sets_owner_id'), ['owner_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('paper', sa.String(length=20), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('skill', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_year'), ['year'], unique=False)

    op.create_table('student_badges',
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('badge_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'badge_id')
    )
    op.create_table('student_subjects',
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'subject_id')
    )
    op.create_table('student_topic_progress',
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('recent_score', sa.Float(), nullable=False),
    sa.Column('historical_score', sa.Float(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('quizzes_completed', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'topic_id')
    )
    with op.batch_alter_table('student_topic_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_topic_progress_subject_id'), ['subject_id'], unique=False)

    op.create_table('ai_interactions',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('question_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('teacher_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('set_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('class_students',
    sa.Column('class_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'student_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('post_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('current_slide', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'lesson_id')
    )
    op.create_table('lesson_slides',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slide_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_slides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_slides_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('post_votes',
    sa.Column('post_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('question_attempts',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('question_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('set_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('context', sa.String(length=20), nullable=False),
    sa.Column('time_spent_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['question_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_set_id'), ['set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_topic_id'), ['topic_id'], unique=False)

    op.create_table('question_set_questions',
    sa.Column('set_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('question_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'question_id')
    )
    op.create_table('teacher_subjects',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('teacher_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('class_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'class_id')
    )
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_subjects_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('assignment_students',
    sa.Column('assignment_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_students')
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_subjects_teacher_id'))

    op.drop_table('teacher_subjects')
    op.drop_table('question_set_questions')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_topic_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_set_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_created_at'))

    op.drop_table('question_attempts')
    op.drop_table('post_votes')
    with op.batch_alter_table('lesson_slides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_slides_lesson_id'))

    op.drop_table('lesson_slides')
    op.drop_table('lesson_progress')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))

    op.drop_table('comments')
    op.drop_table('class_students')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_teacher_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_interactions_created_at'))

    op.drop_table('ai_interactions')
    with op.batch_alter_table('student_topic_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_topic_progress_subject_id'))

    op.drop_table('student_topic_progress')
    op.drop_table('student_subjects')
    op.drop_table('student_badges')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_year'))
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_questions_status'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))

    op.drop_table('questions')
    with op.batch_alter_table('question_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_sets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_question_sets_kind'))

    op.drop_table('question_sets')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_space'))
        batch_op.drop_index(batch_op.f('ix_posts_school_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))

    op.drop_table('posts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_topic_id'))

    op.drop_table('lessons')
    op.drop_table('classes')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))

    op.drop_table('topics')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_email'))

    op.drop_table('profiles')
    op.drop_table('subjects')
    op.drop_table('schools')
    op.drop_table('badges')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
