const ACTION_LABELS: Record<string, string> = {
  "user.create": "Account created",
  "user.role_change": "Role changed",
  "auth.password_reset_requested": "Password reset requested",
  "auth.password_reset_completed": "Password reset completed",
  "auth.password_changed": "Password changed",
  "user.update": "Account updated",
  "user.disable": "Account disabled",
  "user.reactivate": "Account reactivated",
  "user.invitation_sent": "Invitation sent",
  "user.subjects_update": "Student subjects changed",
  "user.import": "Users imported from CSV",
  "enrolment.enrol": "Student enrolled",
  "enrolment.transfer": "Student transferred",
  "enrolment.withdraw": "Student withdrawn from class",
  "class.create": "Class created",
  "class.update": "Class updated",
  "class.archive": "Class archived",
  "class.restore": "Class restored",
  "teacher_assignment.create": "Teacher assigned",
  "teacher_assignment.delete": "Teacher assignment removed",
  "school.update": "School profile updated",
  "academic_year.create": "Academic year created",
  "academic_year.update": "Academic year updated",
  "academic_year.set_current": "Current academic year changed",
  "academic_term.create": "Term added",
  "academic_term.update": "Term updated",
  "academic_term.delete": "Term deleted",
  "subject.create": "Subject created",
  "subject.update": "Subject updated",
  "subject.status": "Subject status changed",
  "topic.create": "Topic created",
  "topic.update": "Topic updated",
  "topic.status": "Topic status changed",
  "lesson.status": "Lesson status changed",
  "question.update": "Question updated",
  "question.image": "Question image uploaded",
  "memo.create": "Memo drafted",
  "memo.update": "Memo updated",
  "memo.status": "Memo status changed",
  "memo.attachment_add": "Memo attachment added",
  "memo.attachment_remove": "Memo attachment removed",
  "community.post_hide": "Post hidden",
  "community.post_restore": "Post restored",
  "community.post_dismiss": "Post reports dismissed",
  "community.comment_hide": "Comment hidden",
  "community.comment_restore": "Comment restored",
  "community.comment_dismiss": "Comment reports dismissed",
  "calendar.event_created": "Calendar event added",
  "calendar.event_updated": "Calendar event updated",
  "calendar.event_deleted": "Calendar event deleted",
};

export function actionLabel(action: string): string {
  return ACTION_LABELS[action] ?? action.replace(/[._]/g, " ");
}

export function formatWhen(iso: string): string {
  return new Date(iso).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
}
